# Server settings
server:
  port: 8090

grpc:
  client:
    device-grpc-server:
      host: 127.0.0.1
      port: 7052


# DATASOURCE
#spring:
  #datasource:
    #url: jdbc:mysql://mysql:3306/scott_db?useUnicode=true&characterEncoding=utf8
    #username: root
    #password: 123456
    #driver-class-name: com.mysql.cj.jdbc.Driver
